### ISSUE TITLE
nuxt3 issues

### ISSUE THREAD

**Issue by jiblett1000** [tailwindlabs/headlessui#1202]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.5.0

**What browser are you using?**

Chrome, Firefox

**Reproduction URL**

https://github.com/jiblett1000/listbox-test

**Describe your issue**

Various issues on a fresh install using nuxt3 (v3.0.0-27439932.78761c2). 

```
[Vue warn]: provide() can only be used inside setup().
[Vue warn]: provide() can only be used inside setup().
[Vue warn]: inject() can only be used inside setup() or functional components.
TypeError: Cannot read properties of undefined (reading 'listboxState')
    at Proxy.<anonymous> (file:///home/worm/listbox-test/.output/server/node_modules/@headlessui/vue/dist/headlessui.esm.js:4:27645)
    at renderComponentRoot (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:2378:44)
    at renderComponentSubTree (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9930:51)
    at renderComponentVNode (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9869:16)
    at renderVNode (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9965:22)
    at renderVNodeChildren (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9980:9)
    at renderElementVNode (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:10031:17)
    at renderVNode (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9962:17)
    at renderComponentSubTree (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9930:13)
    at renderComponentVNode (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9869:16)
[Vue warn]: inject() can only be used inside setup() or functional components.
TypeError: Cannot read properties of undefined (reading 'buttonRef')
    at setup (file:///home/worm/listbox-test/.output/server/node_modules/@headlessui/vue/dist/headlessui.esm.js:4:28720)
    at callWithErrorHandling (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:1957:22)
    at setupStatefulComponent (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:7517:29)
    at setupComponent (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:7498:11)
    at renderComponentVNode (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9853:17)
    at renderVNode (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9965:22)
    at renderVNodeChildren (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9980:9)
    at renderElementVNode (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:10031:17)
    at renderVNode (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9962:17)
    at renderVNodeChildren (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9980:9)
[Vue warn]: Component ListboxButton  is missing template or render function.
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: inject() can only be used inside setup() or functional components.
TypeError: Cannot read properties of undefined (reading 'listboxState')
    at Proxy.<anonymous> (file:///home/worm/listbox-test/.output/server/node_modules/@headlessui/vue/dist/headlessui.esm.js:4:30755)
    at renderComponentRoot (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:2378:44)
    at renderComponentSubTree (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9930:51)
    at renderComponentVNode (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9869:16)
    at renderVNode (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9965:22)
    at renderComponentSubTree (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9930:13)
    at renderComponentVNode (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9869:16)
    at renderVNode (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9965:22)
    at renderComponentSubTree (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9876:9)
    at renderComponentVNode (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9869:16)
[Vue warn]: provide() can only be used inside setup().
[Vue warn]: provide() can only be used inside setup().
[Vue warn]: inject() can only be used inside setup() or functional components.
TypeError: Cannot read properties of undefined (reading 'listboxState')
    at Proxy.<anonymous> (file:///home/worm/listbox-test/.output/server/node_modules/@headlessui/vue/dist/headlessui.esm.js:4:27645)
    at renderComponentRoot (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:2378:44)
    at renderComponentSubTree (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9930:51)
    at renderComponentVNode (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9869:16)
    at renderVNode (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9965:22)
    at renderVNodeChildren (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9980:9)
    at renderElementVNode (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:10031:17)
    at renderVNode (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9962:17)
    at renderComponentSubTree (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9930:13)
    at renderComponentVNode (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9869:16)
[Vue warn]: inject() can only be used inside setup() or functional components.
TypeError: Cannot read properties of undefined (reading 'buttonRef')
    at setup (file:///home/worm/listbox-test/.output/server/node_modules/@headlessui/vue/dist/headlessui.esm.js:4:28720)
    at callWithErrorHandling (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:1957:22)
    at setupStatefulComponent (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:7517:29)
    at setupComponent (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:7498:11)
    at renderComponentVNode (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9853:17)
    at renderVNode (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9965:22)
    at renderVNodeChildren (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9980:9)
    at renderElementVNode (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:10031:17)
    at renderVNode (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9962:17)
    at renderVNodeChildren (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9980:9)
[Vue warn]: Component ListboxButton  is missing template or render function.
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: inject() can only be used inside setup() or functional components.
TypeError: Cannot read properties of undefined (reading 'listboxState')
    at Proxy.<anonymous> (file:///home/worm/listbox-test/.output/server/node_modules/@headlessui/vue/dist/headlessui.esm.js:4:30755)
    at renderComponentRoot (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:2378:44)
    at renderComponentSubTree (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9930:51)
    at renderComponentVNode (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9869:16)
    at renderVNode (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9965:22)
    at renderComponentSubTree (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9930:13)
    at renderComponentVNode (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9869:16)
    at renderVNode (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9965:22)
    at renderComponentSubTree (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9876:9)
    at renderComponentVNode (file:///home/worm/listbox-test/.output/server/chunks/index.mjs:9869:16)
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should have already been fixed. With the repro you shared I can't reproduce this:
<img width="664" alt="image" src="https://user-images.githubusercontent.com/1834413/157011800-827cc71c-d4ed-450d-91bc-49cbecf7647d.png">

Make sure that you remove any caches:
```sh
rm -rf .nuxt .output node_modules
yarn
```

And try again, that should fix those issues.

**Comment by jiblett1000** [comment]
@RobinMalfait Sorry, that didn't do the trick on my end. I realized I forgot to mention this happens after build (when accessing in browser) not during dev.

**Comment by RobinMalfait** [comment]
Aha I see what you mean. This is unfortunately a Nuxt issue and not a Headless UI issue.
We had a similar issue report recently, some more information can be found here https://github.com/tailwindlabs/headlessui/issues/982#issuecomment-1026007771

**Comment by jiblett1000** [comment]
Got it. Thanks for the link!
