### ISSUE TITLE
[plugin server-bare-modules] Package subpath './package.json' is not defined by "exports"

### ISSUE THREAD

**Issue by asciant** [tailwindlabs/headlessui#1313]
**What package within Headless UI are you using?**

`@headlessui/react`

**What version of that package are you using?**

`1.5.0`

**What browser are you using?**

`Chrome`

**Reproduction URL**

[https://github.com/asciant/headlessui-remix-error](https://github.com/asciant/headlessui-remix-error)

**Describe your issue**

@headlessui does not appear to work with `@remix-run`. It throws the following error and crashes.

I tried creating a new remix app with `npx create-remix@latest` and then ran `npm install @headlessui/react`. As soon as I add a `@headlessui/react` component the app crashes.

I tried on node 14x and 16x.

```
➜  my-remix-app git:(main) npm run dev

> dev
> remix dev

Watching Remix app in development mode...

✘ [ERROR] [plugin server-bare-modules] Package subpath './package.json' is not defined by "exports" in /Users/asciant/Projects/my-remix-app/node_modules/@headlessui/react/package.json

    node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:125:32:
      125 │   let packageJsonFile = require.resolve(`${packageName}/package.j...
          ╵                                 ^

    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:453:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:731:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at warnOnceIfEsmOnlyPackage (/Users/asciant/Projects/my-remix-app/node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:125:33)
    at /Users/asciant/Projects/my-remix-app/node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:95:11
    at callback (/Users/asciant/Projects/my-remix-app/node_modules/esbuild/lib/main.js:920:34)

  This error came from the "onResolve" callback registered here:

    node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:46:12:
      46 │       build.onResolve({
         ╵             ~~~~~~~~~

    at setup (/Users/asciant/Projects/my-remix-app/node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:46:13)
    at handlePlugins (/Users/asciant/Projects/my-remix-app/node_modules/esbuild/lib/main.js:842:23)

  The plugin "server-bare-modules" was triggered by this import

    route:/Users/asciant/Projects/my-remix-app/app/routes/index.tsx:1:27:
      1 │ import { Transition } from '@headlessui/react'
        ╵                            ~~~~~~~~~~~~~~~~~~~


Build failed with 1 error:
node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:125:32: ERROR: [plugin: server-bare-modules] Package subpath './package.json' is not defined by "exports" in /Users/asciant/Projects/my-remix-app/node_modules/@headlessui/react/package.json
💿 Built in 461ms
```

**Comment by jackharrhy** [comment]
I'm running into this same issue with Headless UI, however it seems to be an issue with Remix itself ( https://github.com/remix-run/remix/issues/2691 )

Of which there also seems to be a fix for up that isn't merged just yet ( https://github.com/remix-run/remix/pull/2694 )

**Comment by asciant** [comment]
Thanks Jack, you're right explicitly downgrading to `1.3.4` did it. I got caught out by the `^`, which meant `1.3.5` kept being installed by npm.
