### ISSUE TITLE
error when import dialog

### ISSUE THREAD

**Issue by TangsWang** [tailwindlabs/headlessui#1415]
### Discussed in https://github.com/tailwindlabs/headlessui/discussions/1414

<div type='discussions-op-text'>

<sup>Originally posted by **TangsWang** May  6, 2022</sup>

    "@headlessui/vue": "^1.6.1",
    "@heroicons/vue": "^1.0.6",

```
<script setup lang="ts">
import {
  Dialog,
  DialogPanel,
  DialogTitle,
  DialogDescription,
} from '@headlessui/vue'

const isOpen = ref(true)

function setIsOpen(value) {
  isOpen.value = value
}
</script>
```

then error in chrome, like this:

[Headless UI]: Cannot find ownerDocument for contextElement: null
```

at v (/D:/NodeJsWS/my-nuxt3-app/node_modules/@headlessui/vue/dist/components/portal/portal.js:1:364)
at setup (/D:/NodeJsWS/my-nuxt3-app/node_modules/@headlessui/vue/dist/components/portal/portal.js:1:774)
at callWithErrorHandling (D:\NodeJsWS\my-nuxt3-app\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:157:22)
at setupStatefulComponent (D:\NodeJsWS\my-nuxt3-app\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7027:29)
at setupComponent (D:\NodeJsWS\my-nuxt3-app\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:6982:11)
at renderComponentVNode (D:\NodeJsWS\my-nuxt3-app\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:198:17)
at renderVNode (D:\NodeJsWS\my-nuxt3-app\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:310:22)
at renderComponentSubTree (D:\NodeJsWS\my-nuxt3-app\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:275:13)
at renderComponentVNode (D:\NodeJsWS\my-nuxt3-app\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:214:16)
at renderVNode (D:\NodeJsWS\my-nuxt3-app\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:310:22)
```</div>

**Comment by TangsWang** [comment]
@RobinMalfait could you help me?, please.
