### ISSUE TITLE
Error during SSR Rendering (Next 13 , Turbopack)

### ISSUE THREAD

**Issue by carlosbaraza** [tailwindlabs/headlessui#1980]
**What package within Headless UI are you using?**

For example: @headlessui/react

**What version of that package are you using?**

For example: v1.7.3

**What browser are you using?**

For example: Chrome

**Reproduction URL**

Create a new NextJS 13 with Turbopack and app directory. Import and use `@headlessui/combobox`

**Describe your issue**

The SSR rendering of server components fail with Turbopack and NextJS 13:
```
Error during SSR Rendering
  TypeError: __TURBOPACK__imported__module__$5b$project$2d$with$2d$next$5d2f$node_modules$2f$next$2f$dist$2f$compiled$2f$react$2f$react$2e$shared$2d$subset$2e$js__.createContext is not a function
    at <unknown> (/node_modules/@headlessui/react/dist/internal/open-closed.js:1:65)
    at Module.[project-with-next]/node_modules/@headlessui/react/dist/internal/open-closed.js (ecmascript, rsc) (.next/server/app/chunks/rsc/node_modules_@headlessui_react_dist_headlessui.esm.js:4866:3)
    at <unknown> (.next/server/app/chunks/ssr/_9c87dd.js:58485:21)
    at runModuleExecutionHooks (.next/server/app/chunks/ssr/_9c87dd.js:58523:5)
    at instantiateModule (.next/server/app/chunks/ssr/_9c87dd.js:58484:5)
    at getOrInstantiateModuleFromParent (.next/server/app/chunks/ssr/_9c87dd.js:58565:12)
    at esmImport (.next/server/app/chunks/ssr/_9c87dd.js:58294:20)
    at <unknown> (.next/server/app/chunks/rsc/node_modules_@headlessui_react_dist_headlessui.esm.js:70:155)
    at Module.[project-with-next]/node_modules/@headlessui/react/dist/components/combobox/combobox.js (ecmascript, rsc) (.next/server/app/chunks/rsc/node_modules_@headlessui_react_dist_headlessui.esm.js:692:3)
    at <unknown> (.next/server/app/chunks/ssr/_9c87dd.js:58485:21)
    at runModuleExecutionHooks (.next/server/app/chunks/ssr/_9c87dd.js:58523:5)
    at instantiateModule (.next/server/app/chunks/ssr/_9c87dd.js:58484:5)
    at getOrInstantiateModuleFromParent (.next/server/app/chunks/ssr/_9c87dd.js:58565:12)
    at esmImport (.next/server/app/chunks/ssr/_9c87dd.js:58294:20)
    at <unknown> (.next/server/app/chunks/rsc/node_modules_@headlessui_react_dist_headlessui.esm.js:19:163)
    at Module.[project-with-next]/node_modules/@headlessui/react/dist/headlessui.esm.js (ecmascript, rsc) (.next/server/app/chunks/rsc/node_modules_@headlessui_react_dist_headlessui.esm.js:45:3)
    at <unknown> (.next/server/app/chunks/ssr/_9c87dd.js:58485:21)
    at runModuleExecutionHooks (.next/server/app/chunks/ssr/_9c87dd.js:58523:5)
    at instantiateModule (.next/server/app/chunks/ssr/_9c87dd.js:58484:5)
    at getOrInstantiateModuleFromParent (.next/server/app/chunks/ssr/_9c87dd.js:58565:12)
    at esmImport (.next/server/app/chunks/ssr/_9c87dd.js:58294:20)
    at <unknown> (.next/server/app/chunks/rsc/app_layout.tsx.js:36:146)
    at Module.[project-with-next]/app/Navbar.tsx (ecmascript, rsc) (.next/server/app/chunks/rsc/app_layout.tsx.js:227:3)
    at <unknown> (.next/server/app/chunks/ssr/_9c87dd.js:58485:21)
    at runModuleExecutionHooks (.next/server/app/chunks/ssr/_9c87dd.js:58523:5)
    at instantiateModule (.next/server/app/chunks/ssr/_9c87dd.js:58484:5)
    at getOrInstantiateModuleFromParent (.next/server/app/chunks/ssr/_9c87dd.js:58565:12)
    at esmImport (.next/server/app/chunks/ssr/_9c87dd.js:58294:20)
    at <unknown> (.next/server/app/chunks/rsc/app_layout.tsx.js:9:94)
    at Module.[project-with-next]/app/layout.tsx (ecmascript, rsc) (.next/server/app/chunks/rsc/app_layout.tsx.js:28:3)
    at <unknown> (.next/server/app/chunks/ssr/_9c87dd.js:58485:21)
    at runModuleExecutionHooks (.next/server/app/chunks/ssr/_9c87dd.js:58523:5)
    at instantiateModule (.next/server/app/chunks/ssr/_9c87dd.js:58484:5)
    at getOrInstantiateModuleFromParent (.next/server/app/chunks/ssr/_9c87dd.js:58565:12)
    at esmImport (.next/server/app/chunks/ssr/_9c87dd.js:58294:20)
    at <unknown> (.next/server/app/chunks/rsc/app_layout.tsx_layout-entry.tsx.js:22:94)
    at Module.[project-with-next]/app/layout.tsx/layout-entry.tsx (ecmascript, rsc) (.next/server/app/chunks/rsc/app_layout.tsx_layout-entry.tsx.js:34:3)
    at <unknown> (.next/server/app/chunks/ssr/_9c87dd.js:58485:21)
    at runModuleExecutionHooks (.next/server/app/chunks/ssr/_9c87dd.js:58523:5)
    at instantiateModule (.next/server/app/chunks/ssr/_9c87dd.js:58484:5)
    at getOrInstantiateModuleFromParent (.next/server/app/chunks/ssr/_9c87dd.js:58565:12)
    at esmImport (.next/server/app/chunks/ssr/_9c87dd.js:58294:20)
    at Module.default (.next/server/app/chunks/rsc/app_layout.tsx_layout-entry.tsx_with-client-chunks.js:6:18)
    at <unknown> (/app/entry:11:44)
    at Module.[project-with-next]/app/entry (ecmascript, ssr) (.next/server/app/chunks/ssr/_9c87dd.js:317:3)
    at <unknown> (.next/server/app/chunks/ssr/_9c87dd.js:58485:21)
    at runModuleExecutionHooks (.next/server/app/chunks/ssr/_9c87dd.js:58523:5)
    at instantiateModule (.next/server/app/chunks/ssr/_9c87dd.js:58484:5)
    at instantiateRuntimeModule (.next/server/app/chunks/ssr/_9c87dd.js:59069:12)
    at <unknown> (.next/server/app/chunks/ssr/_9c87dd.js:58124:1)
    at <unknown> (.next/server/app/chunks/ssr/_9c87dd.js:59120:39)
    at <anonymous>
    at Object.registerChunk [as push] (.next/server/app/chunks/ssr/_9c87dd.js:59120:25)
    at Object.<anonymous> (.next/server/app/chunks/rsc/node_modules_@headlessui_react_dist_headlessui.esm.js:1:41)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (.next/server/app/index.js:21:1)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at <unknown> (node:internal/main/run_main_module:17:47)
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This might be a Next.js bug or a feature that is not implemented yet, but you can solve it by creating a `components/my-component.js` and make sure there is a `"use client";` at the top:

```js
"use client";

import { Menu } from "@headlessui/react";

export function MyDropdown() {
  return (
    <Menu>
      <Menu.Button>More</Menu.Button>
      <Menu.Items>
        <Menu.Item>
          {({ active }) => (
            <a
              className={`${active && "bg-blue-500"}`}
              href="/account-settings"
            >
              Account settings
            </a>
          )}
        </Menu.Item>
        <Menu.Item>
          {({ active }) => (
            <a
              className={`${active && "bg-blue-500"}`}
              href="/account-settings"
            >
              Documentation
            </a>
          )}
        </Menu.Item>
        <Menu.Item disabled>
          <span className="opacity-75">Invite a friend (coming soon!)</span>
        </Menu.Item>
      </Menu.Items>
    </Menu>
  );
}
```

If you then include this file instead it works as expected.

You can also add the `"use client";` directive to the page itself, but then you lose SSR support. E.g.: `getServerSideProps` will then fail to compile, but it also looks like that's not supported (yet?) in the `app/` directory anyway.

```
Error: getServerSideProps is not supported in app/, detected in
```

---

You can also reproduce this kind of issue without Headless UI entirely. For example create a new page in your app folder:
```js
// app/page.js
import { useMyContext } from "../components/example";


export default function Home(props) {
  useMyContext()

  return <div>Hi</div>;
}
```

Then create a `components/example.js`
```js
import { createContext, useContext } from "react";

let MyContext = createContext()

export function useMyContext() {
  return useContext(MyContext)
}
```

If you would now start your dev server you will receive the following error(s):
```
error - ./components/example.js

You're importing a component that needs createContext. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.

   ,----
 1 | import { createContext, useContext } from "react";
   :          ^^^^^^^^^^^^^
   `----

Maybe one of these should be marked as a client entry with "use client":
  components/example.js
  app/page.js
```

So hopefully the `"use client";` works for you!

**Comment by carlosbaraza** [comment]
Thanks @RobinMalfait. I guess we still need to get used to the whole `"use client";` thing. Although it bothers me that those components would return no html at all, which would hurt SEO. I wonder why `createContext` can't be used in server components. Seems like a common enough API to be supported. In any case, that's not a `headlessui` issue.

**Comment by RobinMalfait** [comment]
@carlosbaraza hey! I was not 100% correct. If you use "use client" you still get SSR, but they don't work as server components. A but confusing but SEO should still be fine.

We also added the client-only package to Headless UI which should improve the error message when using Headless UI directly in a Next.js page.

**Comment by carlosbaraza** [comment]
@RobinMalfait I see. It's definitely confusing cause next could run client components in the server. Thank you for the response.
