### ISSUE TITLE
Unhandled error during execution of setup function: TypeError: Cannot read properties of undefined (reading 'panelId')

### ISSUE THREAD

**Issue by boclifton-MSFT** [tailwindlabs/headlessui#2049]
**What package within Headless UI are you using?**

"@headlessui/vue": "^1.7.4"

**What browser are you using?**

Edge Version 107.0.1418.56 (Official build) (64-bit)

**Reproduction URL**

[Repro repo](https://github.com/dochoss/headlessui-panelid-issue-repro)

**Describe your issue**

EDIT: Issue seems to be inconsistent...after submitting this issue, I deleted the copied code in the Nav component and replaced it with just the text "nav".  This worked as expected and produced only the word "nav" on the screen.  When undoing that update (adding back in the copied navbar code) and saving while the Nuxt project is running, the navbar appeared as initially expected.  When adding back the NuxtWelcome component by removing the comment tags (i.e. changing `<!-- <NuxtWelcome /> -->` to `<NuxtWelcome />`) the NuxtWelcome component appears properly with the navbar above it.  Stopping the Nuxt project and restarting it again produces the bug.

- Set up new Nuxt 3 project following instructions [here](https://tailwindcss.com/docs/guides/nuxtjs#3)
- Installed HeadlessUI and Hero Icons per instructions [here](https://tailwindui.com/documentation#vue-installing-dependencies)
- Copied code from navbar component (tested with multiple, all get same result) in Tailwind UI components page [here](https://tailwindui.com/components/application-ui/navigation/navbars)
- `npm run dev` produces the following stack trace:

```
[Vue warn]: provide() can only be used inside setup().                                                        15:23:12
[Vue warn]: provide() can only be used inside setup().                                                        15:23:12
[Vue warn]: inject() can only be used inside setup() or functional components.                                15:23:12
[Vue warn]: inject() can only be used inside setup() or functional components.                                15:23:12
[Vue warn]: Unhandled error during execution of setup function                                                15:23:12
  at <DisclosureButton class="inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500" >
[nitro] [dev] [unhandledRejection] TypeError: Cannot read properties of undefined (reading 'panelId')         15:23:12
    at setup (file:///c:/Users/boclifton/Source/Repos/nuxt3test/node_modules/@headlessui/vue/dist/components/disclosure/disclosure.js:1:1869)
    at callWithErrorHandling (C:\Users\boclifton\Source\Repos\nuxt3test\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:157:22)
    at setupStatefulComponent (C:\Users\boclifton\Source\Repos\nuxt3test\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7176:29)
    at setupComponent (C:\Users\boclifton\Source\Repos\nuxt3test\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7131:11)
    at renderComponentVNode (C:\Users\boclifton\Source\Repos\nuxt3test\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:172:17)
    at renderVNode (C:\Users\boclifton\Source\Repos\nuxt3test\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:299:22)
    at renderVNodeChildren (C:\Users\boclifton\Source\Repos\nuxt3test\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:314:9)
    at renderElementVNode (C:\Users\boclifton\Source\Repos\nuxt3test\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:365:17)
    at renderVNode (C:\Users\boclifton\Source\Repos\nuxt3test\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:296:17)
    at renderVNodeChildren (C:\Users\boclifton\Source\Repos\nuxt3test\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:314:9)
```

Error image:
![image](https://user-images.githubusercontent.com/102168009/204385541-35467a59-a7df-4582-9a0b-dd9df1428c7a.png)

**Comment by thecrypticace** [comment]
Hey! So the errors you see indicate that there are multiple Vue installations running at one time. This is a known issue with Nuxt 3 (which, honestly, I thought they had fixed but apparently not because I can reproduce this — though only on Windows weirdly enough).

You can work around this by forcing Nuxt to transpile Headless UI by adding a `build.transpile` key to your Nuxt Config:
```diff
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  css: ["~/assets/css/main.css"],
  postcss: {
    plugins: {
      tailwindcss: {},
      autoprefixer: {},
    },
  },
  build: {
    transpile: [
      "@headlessui/vue",
    ],
  },
});
```

The reason this happens is because the SSR build for Nuxt 3 has Vue "embedded" rather than linking an external dependency. However, Headless UI has imports from `vue` and ends up including and linking to a second install inside `node_modules`. So, the `currentInstance` read by headless UI is _different_ than the one used by the server build of Nuxt. This results in these weird errors. Adding Headless UI to the transpile list fixes this problem (and in fact, you may need to do this for _any_ external Vue library used by the SSR build).

**Comment by boclifton-MSFT** [comment]
That did the trick.  Thanks so much @thecrypticace!
