### ISSUE TITLE
Import @headlessui/tailwindcss in tailwind.config

### ISSUE THREAD

**Issue by mcube27** [tailwindlabs/headlessui#2074]
@headlessui/tailwindcss latest

I tried to install the plugin using an import
`import headless from '@headlessui/tailwindcss';`

But I got this error:
```
Failed to resolve entry for package "@headlessui/tailwindcss". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." entry in
 "@headlessui/tailwindcss" package
14:21:15 [vite] Internal server error: Failed to resolve entry for package "@headlessui/tailwindcss". The package may have incorrect main/module/exports specified in its package.jso
n: No known conditions for "." entry in "@headlessui/tailwindcss" package
  Plugin: vite:import-analysis
  File: C:/webserver/www/weeezy-client/tailwind.config.js
      at packageEntryFailure (file:///C:/webserver/www/weeezy-client/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:34100:11)
      at resolvePackageEntry (file:///C:/webserver/www/weeezy-client/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:34095:9)
      at tryNodeResolve (file:///C:/webserver/www/weeezy-client/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:33838:20)
      at Context.resolveId (file:///C:/webserver/www/weeezy-client/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:33598:28)
      at async Object.resolveId (file:///C:/webserver/www/weeezy-client/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:40156:32)
      at async TransformContext.resolve (file:///C:/webserver/www/weeezy-client/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:39921:23)
      at async normalizeUrl (file:///C:/webserver/www/weeezy-client/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:36831:34)
      at async TransformContext.transform (file:///C:/webserver/www/weeezy-client/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:36972:47)
      at async Object.transform (file:///C:/webserver/www/weeezy-client/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:40228:30)
      at async loadAndTransform (file:///C:/webserver/www/weeezy-client/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:36615:29)
14:35:01 [vite] tailwind.config.js changed, restarting server...
14:35:01 [vite] server restarted.
Failed to resolve entry for package "@headlessui/tailwindcss". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." entry in
 "@headlessui/tailwindcss" package
14:35:27 [vite] Internal server error: Failed to resolve entry for package "@headlessui/tailwindcss". The package may have incorrect main/module/exports specified in its package.jso
n: No known conditions for "." entry in "@headlessui/tailwindcss" package
  Plugin: vite:import-analysis
  File: C:/webserver/www/weeezy-client/tailwind.config.js
      at packageEntryFailure (file:///C:/webserver/www/weeezy-client/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:34100:11)
      at resolvePackageEntry (file:///C:/webserver/www/weeezy-client/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:34095:9)
      at tryNodeResolve (file:///C:/webserver/www/weeezy-client/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:33838:20)
      at Context.resolveId (file:///C:/webserver/www/weeezy-client/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:33598:28)
      at async Object.resolveId (file:///C:/webserver/www/weeezy-client/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:40156:32)
      at async TransformContext.resolve (file:///C:/webserver/www/weeezy-client/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:39921:23)
      at async normalizeUrl (file:///C:/webserver/www/weeezy-client/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:36831:34)
      at async TransformContext.transform (file:///C:/webserver/www/weeezy-client/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:36972:47)
      at async Object.transform (file:///C:/webserver/www/weeezy-client/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:40228:30)
      at async loadAndTransform (file:///C:/webserver/www/weeezy-client/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:36615:29)
```
I already have installed the form plugin form tailwind this way with no issue

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

You probably just want to use a `require` instead of an `import` since the `tailwind.config.js` file is currently cjs:

```js

module.exports = {
  // ...
  plugins: [
    // ...
    require('@headlessui/tailwindcss')
  ]
}
```

If this is still a problem, please open a new issue with a minimal reproduction repo attached.

**Comment by mcube27** [comment]
I use vite and can't use require as of my config.

**Comment by alexiscolin** [comment]
Yeah, I've the same issue. Also using vite.
