### ISSUE TITLE
React Demo not work

### ISSUE THREAD

**Issue by singleseeker** [tailwindlabs/headlessui#234]
```
import { useState } from 'react'
import { Transition } from '@headlessui/react'

export default function Dropdown() {
  const [isOpen, setIsOpen] = useState(false)
  return (
    <div className="relative ...">
      <button type="button" onClick={() => setIsOpen(!isOpen)} className="...">
        Options
      </button>

      <Transition
        show={isOpen}
        enter="transition ease-out duration-100 transform"
        enterFrom="opacity-0 scale-95"
        enterTo="opacity-100 scale-100"
        leave="transition ease-in duration-75 transform"
        leaveFrom="opacity-100 scale-100"
        leaveTo="opacity-0 scale-95"
      >
        {(ref) => (
          <div ref={ref} className="absolute right-0 w-56 mt-2 origin-top-right rounded-md shadow-lg">
            <div className="bg-white rounded-md shadow-xs">
              {/* Snipped */}
            </div>
          </div>
        )}
      </Transition>
    </div>
  )
}
```

react with the demo, not work, get an error
```
index.js:1 Warning: Unexpected ref object provided for div. Use either a ref-setter function or React.createRef().
    at div
    at div
    at TransitionChild (http://localhost:3000/static/js/vendors~main.chunk.js:644:27)
    at Transition (http://localhost:3000/static/js/vendors~main.chunk.js:758:20)
    at div
    at Dropdown (http://localhost:3000/static/js/main.chunk.js:2744:85)
    at nav
    at div
    at div
    at div
    at header
    at div
    at App
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

We've updated the API of the Transition component, but I still have to update the example. You can find the new goodies and upgrade path here: https://github.com/tailwindlabs/headlessui/releases/tag/%40headlessui%2Freact%40v0.3.0

To help you out on this one, try something like this:

```js
import { useState } from 'react'
import { Transition } from '@headlessui/react'

export default function Dropdown() {
  const [isOpen, setIsOpen] = useState(false)
  return (
    <div className="relative ...">
      <button type="button" onClick={() => setIsOpen(!isOpen)} className="...">
        Options
      </button>

      <Transition
        show={isOpen}
        enter="transition ease-out duration-100 transform"
        enterFrom="opacity-0 scale-95"
        enterTo="opacity-100 scale-100"
        leave="transition ease-in duration-75 transform"
        leaveFrom="opacity-100 scale-100"
        leaveTo="opacity-0 scale-95"
        className="absolute right-0 w-56 mt-2 origin-top-right rounded-md shadow-lg"
      >
        <div className="bg-white rounded-md shadow-xs">
          {/* Snippet */}
        </div>
      </Transition>
    </div>
  )
}
```

Hope this helps!
