### ISSUE TITLE
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/@headlessui_react.js' does not provide an export named 'DataInteractive' (at link.tsx:8:10)

### ISSUE THREAD

**Issue by divmgl** [tailwindlabs/headlessui#2897]
Anyone else seeing this error when booting up their apps with the new link?

```
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/@headlessui_react.js?v=b77dd52a' does not provide an export named 'DataInteractive' (at link.tsx:8:10)
```

Followed the guide on https://catalyst.tailwindui.com

_Originally posted by @divmgl in https://github.com/tailwindlabs/headlessui/discussions/2895_

**Comment by divmgl** [comment]
Seeing this again, now with `Description`.

```tsx
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/@headlessui_react.js?v=ba705461' does not provide an export named 'Description' (at fieldset.tsx:2:3)
```

I've confirmed @headlessui/react is at latest.

**Comment by divmgl** [comment]
Looks like a previous version was cached.
