### ISSUE TITLE
[Bug]: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by productdevbook** [tailwindlabs/headlessui#866]
### What package within Headless UI are you using?

@heroicons/vue

### What version of that package are you using?

1.0.4

### What browser are you using?

Chrome

### Reproduction repository

https://github.com/productdevbook/nuxt3-app

### Describe your issue

1. yarn install
2. yarn dev
3. http://localhost:3000/modal reload

import { cloneVNode, h, onUnmounted, ref, watchEffect, onUpdated, inject, provide, defineComponent, Teleport, reactive, computed, unref, onMounted, nextTick, toRaw, watch } from 'vue';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async __instantiateModule__ (file://Documents/GitHub/nuxt3-app/.nuxt/dist/server/server.mjs:2784:3)

**Comment by Neewd** [comment]
I have the same issue on my side :(

**Comment by MinSomai** [comment]
same issue
