### ISSUE TITLE
Nuxt 3 document is not defined

### ISSUE THREAD

**Issue by productdevbook** [tailwindlabs/headlessui#903]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

"@headlessui/vue": "^1.4.2",

**What browser are you using?**

Chrome

**Reproduction URL**

Branch: headlessui-next
https://github.com/productdevbook/nuxt3-app/tree/headlessui-next

**Describe your issue**

http://localhost:3000/modal refresh and problem.

**Comment by AxelBriche** [comment]
Any update for resolve this problem please?

**Comment by surfer77** [comment]
Also interested in this

**Comment by AxelBriche** [comment]
Same error on my project, it's a headlessui or nuxt problem please?

**Comment by vanling** [comment]
Some details that might help later 
```
[Vue warn]: Unhandled error during execution of watcher callback 
  at <Dialog as="div" class="fixed inset-0 overflow-hidden" onClose=fn<onClose>  ... >
[Vue warn]: Unhandled error during execution of setup function 
  at <Dialog as="div" class="fixed inset-0 overflow-hidden" onClose=fn<onClose>  ... >
document is not defined
  at file://./.nuxt/dist/server/server.mjs:4979:22  
  at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6621:22)  
  at callWithAsyncErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6630:21)  
  at getter (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6976:24)  
  at doWatch (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7000:13)  
  at Module.watchEffect (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6896:12)  
  at setup (file://./.nuxt/dist/server/server.mjs:4977:27)  
  at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6621:22)  
  at setupStatefulComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6247:29)  
  at setupComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6203:11)
```
  
  
  ```<template>
  <div>
    <TransitionRoot as="template" :show="open">
      <Dialog
        as="div"
        class="fixed inset-0 overflow-hidden"
        @close="open = false"
      >```

**Comment by misaon** [comment]
@vanling and only with `TransitionRoot `root element

**Comment by phphe** [comment]
I use ClientOnly to wrap it.

**Comment by productdevbook** [comment]
this problem has been fixed. You can check the repo. The modal must initially have a false value for it to open and close. 

[https://github.com/productdevbook/nuxt3-app](https://github.com/productdevbook/nuxt3-app/tree/headlessui-next)
