### ISSUE TITLE
HeadlessUI is not working with Nuxt 3

### ISSUE THREAD

**Issue by bayramorhan** [tailwindlabs/headlessui#982]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

```
"devDependencies": {
    "autoprefixer": "^10.4.0",
    "nuxt3": "latest",
    "postcss": "^8.4.4",
    "tailwindcss": "^2.2.19"
  },
  "dependencies": {
    "@headlessui/vue": "^1.4.2",
    "@heroicons/vue": "^1.0.5",
    "@tailwindcss/forms": "^0.3.4"
  }
```

**Describe your issue**

It works fine with development but when I build nuxt (nuxi build) and start (yarn start) it gives error. I've tried to import headless ui component from @headlessui/vue/dist/index.js instead of @headlessui/vue but its still same.

```
TypeError: Cannot read property 'buttonRef' of undefined
    at setup (D:\projects\headless-test\nuxt3-app\.output\server\node_modules\@headlessui\vue\dist\headlessui.cjs.development.js:2622:15)
    at callWithErrorHandling (file:///D:/projects/headless-test/nuxt3-app/.output/server/chunks/index.mjs:7158:22)
    at setupStatefulComponent (file:///D:/projects/headless-test/nuxt3-app/.output/server/chunks/index.mjs:6874:29)
    at setupComponent (file:///D:/projects/headless-test/nuxt3-app/.output/server/chunks/index.mjs:6855:11)
    at renderComponentVNode (file:///D:/projects/headless-test/nuxt3-app/.output/server/chunks/index.mjs:9757:17)
    at renderVNode (file:///D:/projects/headless-test/nuxt3-app/.output/server/chunks/index.mjs:9863:22)
    at renderVNodeChildren (file:///D:/projects/headless-test/nuxt3-app/.output/server/chunks/index.mjs:9878:9)
    at renderElementVNode (file:///D:/projects/headless-test/nuxt3-app/.output/server/chunks/index.mjs:9929:17)
    at renderVNode (file:///D:/projects/headless-test/nuxt3-app/.output/server/chunks/index.mjs:9860:17)
    at renderVNodeChildren (file:///D:/projects/headless-test/nuxt3-app/.output/server/chunks/index.mjs:9878:9)
[Vue warn]: inject() can only be used inside setup() or functional components.
TypeError: Cannot read property 'menuState' of undefined
    at Proxy.render$1 (D:\projects\headless-test\nuxt3-app\.output\server\node_modules\@headlessui\vue\dist\headlessui.cjs.development.js:2522:17)
    at renderComponentRoot (file:///D:/projects/headless-test/nuxt3-app/.output/server/chunks/index.mjs:2015:44)
    at renderComponentSubTree (file:///D:/projects/headless-test/nuxt3-app/.output/server/chunks/index.mjs:9828:51)
    at renderComponentVNode (file:///D:/projects/headless-test/nuxt3-app/.output/server/chunks/index.mjs:9773:16)
    at renderVNode (file:///D:/projects/headless-test/nuxt3-app/.output/server/chunks/index.mjs:9863:22)
    at renderVNodeChildren (file:///D:/projects/headless-test/nuxt3-app/.output/server/chunks/index.mjs:9878:9)
    at renderElementVNode (file:///D:/projects/headless-test/nuxt3-app/.output/server/chunks/index.mjs:9929:17)
    at renderVNode (file:///D:/projects/headless-test/nuxt3-app/.output/server/chunks/index.mjs:9860:17)
    at renderVNodeChildren (file:///D:/projects/headless-test/nuxt3-app/.output/server/chunks/index.mjs:9878:9)
    at renderElementVNode (file:///D:/projects/headless-test/nuxt3-app/.output/server/chunks/index.mjs:9929:17)
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Unhandled error during execution of watcher callback
TypeError: Cannot read property 'itemsRef' of undefined
    at ReactiveEffect.fn (D:\projects\headless-test\nuxt3-app\.output\server\node_modules\@headlessui\vue\dist\headlessui.cjs.development.js:2685:24)
    at ReactiveEffect.run (D:\projects\headless-test\nuxt3-app\.output\server\node_modules\@vue\reactivity\dist\reactivity.cjs.js:164:29)
    at ComputedRefImpl.get value [as value] (D:\projects\headless-test\nuxt3-app\.output\server\node_modules\@vue\reactivity\dist\reactivity.cjs.js:1075:39)
    at D:\projects\headless-test\nuxt3-app\.output\server\node_modules\@headlessui\vue\dist\headlessui.cjs.development.js:2336:26
    at callWithErrorHandling (D:\projects\headless-test\nuxt3-app\.output\server\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:6615:22)
    at callWithAsyncErrorHandling (D:\projects\headless-test\nuxt3-app\.output\server\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:6624:21)
    at ReactiveEffect.getter [as fn] (D:\projects\headless-test\nuxt3-app\.output\server\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:6970:24)
    at ReactiveEffect.run (D:\projects\headless-test\nuxt3-app\.output\server\node_modules\@vue\reactivity\dist\reactivity.cjs.js:164:29)
    at doWatch (D:\projects\headless-test\nuxt3-app\.output\server\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7078:16)
    at Object.watchEffect (D:\projects\headless-test\nuxt3-app\.output\server\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:6890:12)
[Vue warn]: inject() can only be used inside setup() or functional components.
TypeError: Cannot read property 'menuState' of undefined
    at Proxy.render$1 (D:\projects\headless-test\nuxt3-app\.output\server\node_modules\@headlessui\vue\dist\headlessui.cjs.development.js:2656:17)
    at renderComponentRoot (file:///D:/projects/headless-test/nuxt3-app/.output/server/chunks/index.mjs:2015:44)
    at renderComponentSubTree (file:///D:/projects/headless-test/nuxt3-app/.output/server/chunks/index.mjs:9828:51)
    at renderComponentVNode (file:///D:/projects/headless-test/nuxt3-app/.output/server/chunks/index.mjs:9773:16)
    at renderVNode (file:///D:/projects/headless-test/nuxt3-app/.output/server/chunks/index.mjs:9863:22)
    at renderComponentSubTree (file:///D:/projects/headless-test/nuxt3-app/.output/server/chunks/index.mjs:9828:13)
    at renderComponentVNode (file:///D:/projects/headless-test/nuxt3-app/.output/server/chunks/index.mjs:9773:16)
    at renderVNode (file:///D:/projects/headless-test/nuxt3-app/.output/server/chunks/index.mjs:9863:22)
    at renderComponentSubTree (file:///D:/projects/headless-test/nuxt3-app/.output/server/chunks/index.mjs:9780:9)
    at renderComponentVNode (file:///D:/projects/headless-test/nuxt3-app/.output/server/chunks/index.mjs:9773:16)

```

**Comment by bencehusi** [comment]
+1 on this one.

**Comment by akdenizbengisu** [comment]
+1

**Comment by cgrlcr** [comment]
+1

**Comment by vanling** [comment]
It works for me with the following package.json/versions

```
{
  "private": true,
  "scripts": {
    "dev": "nuxi dev",
    "build": "nuxi build",
    "start": "node .output/server/index.mjs"
  },
  "devDependencies": {
    "@headlessui/vue": "^1.4.2",
    "@iconify/json": "^1.1.434",
    "@nuxtjs/eslint-config-typescript": "^7.0.2",
    "@pinia/nuxt": "^0.1.5",
    "@tailwindcss/aspect-ratio": "^0.3.0",
    "@tailwindcss/forms": "^0.3.4",
    "@vueuse/core": "^7.1.2",
    "autoprefixer": "^10.4.0",
    "nuxt3": "latest",
    "pinia": "^2.0.4",
    "postcss": "^8.3.11",
    "tailwindcss": "^2.2.19",
    "unplugin-icons": "^0.12.18"
  },
  "pnpm": {
    "overrides": {
      "@nuxt/kit": "npm:@nuxt/kit-edge@latest",
      "@nuxt/kit-edge": "latest"
    }
  },

}
```

**Comment by bayramorhan** [comment]
Are you trying in development mode or production mode with built files (.output) ?

```
import { Menu, MenuButton, MenuItem, MenuItems } from '@headlessui/vue';

export default {
  layout: 'individual-main',
  components: {
    Menu,
    MenuButton,
    MenuItem,
    MenuItems,
  },
  setup() {...
```

**Comment by bayramorhan** [comment]
> I have it working in both, dev and production build. I didn't try to use them in pages directly, I create components with headlessui parts in it. (should not make a difference) _let me test this right now_

Thank you for your response. I also tried with this nuxt 3 starter but I 've got same error.

https://github.com/productdevbook/nuxt3-app?ref=bestofvue.com

**Comment by vanling** [comment]
Is your default "open" state true? for example `let isOpen = ref(true);` ?

**Comment by bayramorhan** [comment]
Here is my example 

```
<template>
  <div>
    <div class="px-4 sm:px-0">
      <div class="sm:hidden">
        <label for="question-tabs" class="sr-only">Select a tab</label>
        <select
          id="question-tabs"
          class="
            block
            w-full
            rounded-md
            border-gray-300
            text-base
            font-medium
            text-gray-900
            shadow-sm
            focus:border-rose-500 focus:ring-rose-500
          "
        >
          <option v-for="tab in tabs" :key="tab.name" :selected="tab.current">
            {{ tab.name }}
          </option>
        </select>
      </div>
      <div class="hidden sm:block">
        <nav
          class="relative z-0 rounded-lg shadow flex divide-x divide-gray-200"
          aria-label="Tabs"
        >
          <a
            v-for="(tab, tabIdx) in tabs"
            :key="tab.name"
            :href="tab.href"
            :aria-current="tab.current ? 'page' : undefined"
            :class="[
              tab.current
                ? 'text-gray-900'
                : 'text-gray-500 hover:text-gray-700',
              tabIdx === 0 ? 'rounded-l-lg' : '',
              tabIdx === tabs.length - 1 ? 'rounded-r-lg' : '',
              'group relative min-w-0 flex-1 overflow-hidden bg-white py-4 px-6 text-sm font-medium text-center hover:bg-gray-50 focus:z-10',
            ]"
          >
            <span>{{ tab.name }}</span>
            <span
              aria-hidden="true"
              :class="[
                tab.current ? 'bg-rose-500' : 'bg-transparent',
                'absolute inset-x-0 bottom-0 h-0.5',
              ]"
            />
          </a>
        </nav>
      </div>
    </div>
    <div class="mt-4">
      <h1 class="sr-only">Recent questions</h1>
      <ul role="list" class="space-y-4">
        <li
          v-for="question in questions"
          :key="question.id"
          class="bg-white px-4 py-6 shadow sm:p-6 sm:rounded-lg"
        >
          <article :aria-labelledby="'question-title-' + question.id">
            <div>
              <div class="flex space-x-3">
                <div class="flex-shrink-0">
                  <img
                    class="h-10 w-10 rounded-full"
                    :src="question.author.imageUrl"
                    alt=""
                  />
                </div>
                <div class="min-w-0 flex-1">
                  <p class="text-sm font-medium text-gray-900">
                    <a :href="question.author.href" class="hover:underline">{{
                      question.author.name
                    }}</a>
                  </p>
                  <p class="text-sm text-gray-500">
                    <a :href="question.href" class="hover:underline">
                      <time :datetime="question.datetime">{{
                        question.date
                      }}</time>
                    </a>
                  </p>
                </div>
                <div class="flex-shrink-0 self-center flex">
                  <Menu as="div" class="relative inline-block text-left">
                    <div>
                      <MenuButton
                        class="
                          -m-2
                          p-2
                          rounded-full
                          flex
                          items-center
                          text-gray-400
                          hover:text-gray-600
                        "
                      >
                        <span class="sr-only">Open options</span>
                        <DotsVerticalIcon class="h-5 w-5" aria-hidden="true" />
                      </MenuButton>
                    </div>

                    <transition
                      enter-active-class="transition ease-out duration-100"
                      enter-from-class="transform opacity-0 scale-95"
                      enter-to-class="transform opacity-100 scale-100"
                      leave-active-class="transition ease-in duration-75"
                      leave-from-class="transform opacity-100 scale-100"
                      leave-to-class="transform opacity-0 scale-95"
                    >
                      <MenuItems
                        class="
                          origin-top-right
                          absolute
                          right-0
                          mt-2
                          w-56
                          rounded-md
                          shadow-lg
                          bg-white
                          ring-1 ring-black ring-opacity-5
                          focus:outline-none
                        "
                      >
                        <div class="py-1">
                          <MenuItem v-slot="{ active }">
                            <a
                              href="#"
                              :class="[
                                active
                                  ? 'bg-gray-100 text-gray-900'
                                  : 'text-gray-700',
                                'flex px-4 py-2 text-sm',
                              ]"
                            >
                              <StarIcon
                                class="mr-3 h-5 w-5 text-gray-400"
                                aria-hidden="true"
                              />
                              <span>Add to favorites</span>
                            </a>
                          </MenuItem>
                          <MenuItem v-slot="{ active }">
                            <a
                              href="#"
                              :class="[
                                active
                                  ? 'bg-gray-100 text-gray-900'
                                  : 'text-gray-700',
                                'flex px-4 py-2 text-sm',
                              ]"
                            >
                              <CodeIcon
                                class="mr-3 h-5 w-5 text-gray-400"
                                aria-hidden="true"
                              />
                              <span>Embed</span>
                            </a>
                          </MenuItem>
                          <MenuItem v-slot="{ active }">
                            <a
                              href="#"
                              :class="[
                                active
                                  ? 'bg-gray-100 text-gray-900'
                                  : 'text-gray-700',
                                'flex px-4 py-2 text-sm',
                              ]"
                            >
                              <FlagIcon
                                class="mr-3 h-5 w-5 text-gray-400"
                                aria-hidden="true"
                              />
                              <span>Report content</span>
                            </a>
                          </MenuItem>
                        </div>
                      </MenuItems>
                    </transition>
                  </Menu>
                </div>
              </div>
              <h2
                :id="'question-title-' + question.id"
                class="mt-4 text-base font-medium text-gray-900"
              >
                {{ question.title }}
              </h2>
            </div>
            <div
              class="mt-2 text-sm text-gray-700 space-y-4"
              v-html="question.body"
            />
            <div class="mt-6 flex justify-between space-x-8">
              <div class="flex space-x-6">
                <span class="inline-flex items-center text-sm">
                  <button
                    type="button"
                    class="
                      inline-flex
                      space-x-2
                      text-gray-400
                      hover:text-gray-500
                    "
                  >
                    <ThumbUpIcon class="h-5 w-5" aria-hidden="true" />
                    <span class="font-medium text-gray-900">{{
                      question.likes
                    }}</span>
                    <span class="sr-only">likes</span>
                  </button>
                </span>
                <span class="inline-flex items-center text-sm">
                  <button
                    type="button"
                    class="
                      inline-flex
                      space-x-2
                      text-gray-400
                      hover:text-gray-500
                    "
                  >
                    <ChatAltIcon class="h-5 w-5" aria-hidden="true" />
                    <span class="font-medium text-gray-900">{{
                      question.replies
                    }}</span>
                    <span class="sr-only">replies</span>
                  </button>
                </span>
                <span class="inline-flex items-center text-sm">
                  <button
                    type="button"
                    class="
                      inline-flex
                      space-x-2
                      text-gray-400
                      hover:text-gray-500
                    "
                  >
                    <EyeIcon class="h-5 w-5" aria-hidden="true" />
                    <span class="font-medium text-gray-900">{{
                      question.views
                    }}</span>
                    <span class="sr-only">views</span>
                  </button>
                </span>
              </div>
              <div class="flex text-sm">
                <span class="inline-flex items-center text-sm">
                  <button
                    type="button"
                    class="
                      inline-flex
                      space-x-2
                      text-gray-400
                      hover:text-gray-500
                    "
                  >
                    <ShareIcon class="h-5 w-5" aria-hidden="true" />
                    <span class="font-medium text-gray-900">Share</span>
                  </button>
                </span>
              </div>
            </div>
          </article>
        </li>
      </ul>
    </div>
  </div>
</template>

<script>
import {
  ChatAltIcon,
  DotsVerticalIcon,
  EyeIcon,
  ShareIcon,
  ThumbUpIcon,
  StarIcon,
  CodeIcon,
  FlagIcon,
} from '@heroicons/vue/solid/index.js';

import { Menu, MenuButton, MenuItem, MenuItems } from '@headlessui/vue';

export default {
  layout: 'individual-main',
  components: {
    ChatAltIcon,
    DotsVerticalIcon,
    EyeIcon,
    ShareIcon,
    ThumbUpIcon,
    StarIcon,
    CodeIcon,
    FlagIcon,
    Menu,
    MenuButton,
    MenuItem,
    MenuItems,
  },
  setup() {
    const questions = [
      {
        id: '81614',
        likes: '29',
        replies: '11',
        views: '2.7k',
        author: {
          name: 'Dries Vincent',
          imageUrl:
            'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
          href: '#',
        },
        date: 'December 9 at 11:43 AM',
        datetime: '2020-12-09T11:43:00',
        href: '#',
        title: 'What would you have done differently if you ran Jurassic Park?',
        body: `
      <p>Jurassic Park was an incredible idea and a magnificent feat of engineering, but poor protocols and a disregard for human safety killed what could have otherwise been one of the best businesses of our generation.</p>
      <p>Ultimately, I think that if you wanted to run the park successfully and keep visitors safe, the most important thing to prioritize would be&hellip;</p>
    `,
      },
    ];

    const tabs = [
      { name: 'Recent', href: '#', current: true },
      { name: 'Most Liked', href: '#', current: false },
      { name: 'Most Answers', href: '#', current: false },
    ];

    return { questions, tabs };
  },
};
</script>

```

**Comment by vanling** [comment]
I got the same errors now with the Menu components. On page and in when its wrapped in a component. And only in the server on SSR.

```
[Vue warn]: provide() can only be used inside setup().
[Vue warn]: provide() can only be used inside setup().
[Vue warn]: inject() can only be used inside setup() or functional components.
TypeError: Cannot read properties of undefined (reading 'buttonRef')
```

We need to make a small reproduction i think

**Comment by vanling** [comment]
https://codesandbox.io/s/angry-orla-qf02s?file=/pages/index.vue

Opening a new terminal and running `npm run build` && `PORT=4000 node .output/server/index.mjs`

**Comment by misaon** [comment]
+1

**Comment by weleo** [comment]
Adding to this issue as a reminder because there is more than one issue with HeadlessUI x Nuxt 3.

I am getting the following error in **Safari** using the **Disclosure component** in a production environment: 

```TypeError: null is not an object (evaluating 't.insertBefore')```.  

The component _also doesn't work_ in **other browsers**, but it shows no error messages in the console. Hoping to use HeadlessUI in Nuxt 3 sometime in the future 🤞

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders` or `yarn add @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders` or `yarn add @headlessui/vue@insiders`.

**Comment by Blakeinstein** [comment]
>  @headlessui/vue@insiders

This throws an error, 
````
 ERROR  [worker] Cannot use import statement outside a module                                                                                                

  import{defineComponent as X,ref as A,provide as Oo,inject as To,onMounted as st,onUnmounted as Co,computed as w,nextTick as L,watchEffect as pt,toRaw as dt,watch as Ro}from"vue";import{h as so,cloneVNode as po}from"vue";function S(t,n,...a){if(t in n){let o=n[t];return typeof o=="function"?o(...a):o}let e=new Error(`Tried to handle "${t}" but there is no handler defined. Only defined handlers are: ${Object.keys(n).map(o=>`"${o}"`).join(", ")}.`);throw Error.captureStackTrace&&Error.captureStackTrace(e,S),e}function g({visible:t=!0,features:n=0,...a}){if(t||n&2&&a.props.static)return ye(a);if(n&1){let e=a.props.unmount??!0?0:1;return S(e,{[0](){return null},[1](){return ye({...a,props:{...a.props,hidden:!0,style:{display:"none"}}})}})}return ye(a)}function ye({props:t,attrs:n,slots:a,slot:e,name:o}){let{as:r,...u}=D(t,["unmount","static"]),p=a.default?.(e);if(r==="template"){if(Object.keys(u).length>0||Object.keys(n).length>0){let[l,...i]=p??[];if(!fo(l)||i.length>0)throw new Error(['Passing props on "template"!',"",`The current component <${o} /> is rendering a "template".`,"However we need to passthrough the following props:",Object.keys(u).concat(Object.keys(n)).map(s=>`  - ${s}`).join(`
  ^^^^^^
  
  SyntaxError: Cannot use import statement outside a module
  at Object.compileFunction (node:vm:352:18)
  at wrapSafe (node:internal/modules/cjs/loader:1031:15)
  at Module._compile (node:internal/modules/cjs/loader:1065:27)
  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
  at Module.load (node:internal/modules/cjs/loader:981:32)
  at Function.Module._load (node:internal/modules/cjs/loader:822:12)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:190:29)
  at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
```

**Comment by Raymonf** [comment]
Hello! It doesn't seem to work with Vite, either, after compilation:

```
(base) raymonf@Raymonf-MBP frontend % yarn start      
yarn run v1.22.17
warning ../../../../package.json: No license field
$ node .output/server/index.mjs
Listening on http://localhost:3000/
Named export 'Menu' not found. The requested module '@headlessui/vue' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@headlessui/vue';
const { Menu, TransitionRoot, MenuItems, MenuItem, MenuButton } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)  
  at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)  
  at async Promise.all (index 0)  
  at async ESMLoader.import (node:internal/modules/esm/loader:281:24)  
  at async file://./.output/server/chunks/app/render.mjs:527:24  
  at async renderMiddleware (file://./.output/server/chunks/app/render.mjs:575:20)  
  at async handle (file://./.output/server/node_modules/h3/dist/index.mjs:601:19)
Named export 'Menu' not found. The requested module '@headlessui/vue' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@headlessui/vue';
const { Menu, TransitionRoot, MenuItems, MenuItem, MenuButton } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)  
  at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)  
  at async Promise.all (index 0)  
  at async ESMLoader.import (node:internal/modules/esm/loader:281:24)  
  at async file://./.output/server/chunks/app/render.mjs:527:24  
  at async renderMiddleware (file://./.output/server/chunks/app/render.mjs:575:20)  
  at async handle (file://./.output/server/node_modules/h3/dist/index.mjs:601:19)
```

**Comment by Blakeinstein** [comment]
> Hello! It doesn't seem to work with Vite, either, after compilation:

Strange, the repro when using the insider build was working with the vite bundler, but not webpack

**Comment by Raymonf** [comment]
@Blakeinstein I actually tried it anyways, and for some reason my site _did_ load without problems even though this error was spat out. SSR seemed to be correct, too, with the client not complaining during hydration. I'm not really sure what's happening. 😅

**Comment by Blakeinstein** [comment]
> @Blakeinstein I actually tried it anyways, and for some reason my site _did_ load without problems even though this error was spat out. SSR seemed to be correct, too, with the client not complaining during hydration. I'm not really sure what's happening. sweat_smile

I am myself now getting the same error? I changed the import statement to be
```ts
import * as headlessui from '@headlessui/vue'

const { Popover, PopoverButton, PopoverPanel } = headlessui
```

and now am getting the type: module error as i got in webpack.

@RobinMalfait I think its a bit too early to close this issue.

**Comment by misaon** [comment]
Do you transiple @headlessui/vue package in nuxt.config ?

**Comment by Blakeinstein** [comment]
> Do you transpile @headlessui/vue package in nuxt.config ?
> 
> [v3.nuxtjs.org/concepts/esm/#transpiling-libraries](https://v3.nuxtjs.org/concepts/esm/#transpiling-libraries)

Can confirm this works. But not sure if this is a fix or a workaround.

**Comment by misaon** [comment]
> > Do you transpile @headlessui/vue package in nuxt.config ?
> > [v3.nuxtjs.org/concepts/esm/#transpiling-libraries](https://v3.nuxtjs.org/concepts/esm/#transpiling-libraries)
> 
> Can confirm this works. But not sure if this is a fix or a workaround.

it's definitely a workaround, HeadlessUi needs to work so that it can be imported natively into Nuxt 3 without build bugs.  but for now it is enough for us.

**Comment by RobinMalfait** [comment]
Did a few improvements and it fixes the important parts, it's a proper `type: module` and all cjs files are using `.cjs` instead of `.js.

You can already try it using `npm install @headlessui/vue@insiders` or `yarn add @headlessui/vue@insiders`.

---

Creating a new Nuxt 3 app and loading Headless UI gives me the expected output without console warnings. 
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/1834413/151836981-cbe47774-1775-4774-af6c-37ff2331275b.png">

---

@Blakeinstein When I pull down the repro you provided, and bump to the latest insiders version I linked above then I do get the correct output:
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/1834413/151837175-81e0a6ef-e46b-41c3-a407-4be38393c002.png">

The terminal correctly outputs the following information: 
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/1834413/151838017-5dd687f2-64d7-4c28-be5f-3d85a8950398.png">

However, it looks like there is a server side rendering Nuxt bug once you load the page: 
<img width="2140" alt="image" src="https://user-images.githubusercontent.com/1834413/151838138-3240a069-2316-407b-a2b2-96aa778841c0.png">

After some digging, @thecrypticace found that Nuxt loads 2 versions of Vue which results in these errors because they check if the same instance of Vue is used. But you should get this warning for _any_ external library that depends on Vue, I think.

![image](https://user-images.githubusercontent.com/1834413/151838730-d0176aaa-e436-41cf-a011-43535e9eb187.png)

---

Can somebody verify the latest insiders build?

**Comment by Blakeinstein** [comment]
> Can somebody verify the latest insiders build?

Can confirm that it is fixed, both on vite and on webpack. Apart from said errors. Much thanks!

**Comment by RobinMalfait** [comment]
Thanks for testing, @Blakeinstein!

Going to close this issue, if somebody still has an issue, please open a new issue with a reproduction. Also make sure that for now you have to use the `insiders` build.

**Comment by NidMo** [comment]
> 感谢您的测试，@Blakeinstein！
> 
> 打算关闭这个问题，如果有人仍然有问题，请打开一个带有复制的新问题。还要确保现在您必须使用`insiders`构建。

this problem is nuxt3 bug? how can i use headlessUI in nuxt3? install headlessUI@insiders?

**Comment by Blakeinstein** [comment]
>     2. Add the library for transpiling during build in `nuxt.config.ts|js`

I am using it in prod without adding this package to transpile

**Comment by benoitdemaegdt** [comment]
Hey there 👋 

I'm currently facing very similar issue using headlessui with Nuxt3.

Until version `3.0.0-27447229.20f3171` of Nuxt, everything was working fine 👌 

Then I tried to update latest Nuxt version (current version is `3.0.0-27457855.7c0b914`) and : 
- it still works in dev mode (`npm run dev`)
- it breaks when building and previewing (`npm run build` and `npx nuxi preview`). It also breaks when deploying on vercel or netlify (tried both).

When looking at logs, it seems that errors and warns are coming from headlessui
```
TypeError: Cannot read properties of undefined (reading 'button')
    at setup (/.output/server/node_modules/@headlessui/vue/dist/headlessui.esm.js:4:46368)
```

```
[Vue warn]: Component PopoverButton  is missing template or render function.
```

```
TypeError: Cannot read properties of undefined (reading 'panel')
at setup (/.output/server/node_modules/@headlessui/vue/dist/headlessui.esm.js:4:49526)
```

```
[Vue warn]: Component PopoverPanel  is missing template or render function.
```

I also tried to use `@headlessui/vue@insiders` with no significant change.
Anyone facing similar issue with latest nuxt 3 releases ?

**Comment by benoitdemaegdt** [comment]
These errors are probably coming from Nuxt.

See this github issue : https://github.com/nuxt/framework/issues/3688
And this one : https://github.com/nuxt/framework/issues/2326

**Comment by Blakeinstein** [comment]
> When looking at logs, it seems that errors and warns are coming from headlessui

The thing is, its most likely another error in your code. Those errors can be ignored, but nuxt doesnt report the errors properly making some headlessui events (like expanding popovers) break. I faced this in a particular instance but I cannot recall what error I had, but it was not in headless ui
